import { db } from '@/db';
import { safetyResources } from '@/db/schema';

async function main() {
    const sampleSafetyResources = [
        // Police Stations (8)
        {
            type: 'police',
            name: 'Central Police Station',
            latitude: 40.7580,
            longitude: -73.9855,
            address: '221 West 46th Street, New York, NY 10036',
            phone: '+1-555-101-1001',
            available247: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'police',
            name: 'Downtown Police Precinct',
            latitude: 40.7128,
            longitude: -74.0060,
            address: '5 Beekman Street, New York, NY 10038',
            phone: '+1-555-101-1002',
            available247: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'police',
            name: 'Midtown North Police Station',
            latitude: 40.7614,
            longitude: -73.9776,
            address: '306 West 54th Street, New York, NY 10019',
            phone: '+1-555-101-1003',
            available247: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'police',
            name: 'East Side Police Department',
            latitude: 40.7489,
            longitude: -73.9680,
            address: '153 East 51st Street, New York, NY 10022',
            phone: '+1-555-101-1004',
            available247: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'police',
            name: 'West End Police Station',
            latitude: 40.7851,
            longitude: -73.9763,
            address: '2090 Adam Clayton Powell Jr Boulevard, New York, NY 10027',
            phone: '+1-555-101-1005',
            available247: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'police',
            name: 'Harbor Police Precinct',
            latitude: 40.7060,
            longitude: -74.0130,
            address: '16 Ericsson Place, New York, NY 10013',
            phone: '+1-555-101-1006',
            available247: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'police',
            name: 'Northern District Police Station',
            latitude: 40.8448,
            longitude: -73.9386,
            address: '4295 Broadway, New York, NY 10033',
            phone: '+1-555-101-1007',
            available247: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'police',
            name: 'South District Police Department',
            latitude: 40.6782,
            longitude: -73.9442,
            address: '321 Union Street, Brooklyn, NY 11231',
            phone: '+1-555-101-1008',
            available247: true,
            createdAt: new Date().toISOString(),
        },
        // Hospitals (6)
        {
            type: 'hospital',
            name: 'Metropolitan General Hospital',
            latitude: 40.7484,
            longitude: -73.9857,
            address: '1000 Tenth Avenue, New York, NY 10019',
            phone: '+1-555-202-2001',
            available247: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'hospital',
            name: 'City Medical Center',
            latitude: 40.7410,
            longitude: -73.9937,
            address: '317 East 34th Street, New York, NY 10016',
            phone: '+1-555-202-2002',
            available247: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'hospital',
            name: 'Downtown Emergency Clinic',
            latitude: 40.7150,
            longitude: -74.0070,
            address: '170 William Street, New York, NY 10038',
            phone: '+1-555-202-2003',
            available247: false,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'hospital',
            name: 'Upper East Medical Hospital',
            latitude: 40.7736,
            longitude: -73.9566,
            address: '1275 York Avenue, New York, NY 10065',
            phone: '+1-555-202-2004',
            available247: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'hospital',
            name: 'West Side Community Hospital',
            latitude: 40.7899,
            longitude: -73.9759,
            address: '506 Lenox Avenue, New York, NY 10037',
            phone: '+1-555-202-2005',
            available247: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'hospital',
            name: 'Harbor Medical Center',
            latitude: 40.7035,
            longitude: -74.0135,
            address: '63 Downing Street, New York, NY 10014',
            phone: '+1-555-202-2006',
            available247: false,
            createdAt: new Date().toISOString(),
        },
        // Embassies (3)
        {
            type: 'embassy',
            name: 'United States Embassy',
            latitude: 40.7614,
            longitude: -73.9776,
            address: '799 United Nations Plaza, New York, NY 10017',
            phone: '+1-555-303-3001',
            available247: false,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'embassy',
            name: 'British Consulate General',
            latitude: 40.7580,
            longitude: -73.9720,
            address: '845 Third Avenue, New York, NY 10022',
            phone: '+1-555-303-3002',
            available247: false,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'embassy',
            name: 'Canadian Consulate General',
            latitude: 40.7550,
            longitude: -73.9700,
            address: '466 Lexington Avenue, New York, NY 10017',
            phone: '+1-555-303-3003',
            available247: false,
            createdAt: new Date().toISOString(),
        },
        // Help Centers (3)
        {
            type: 'help_center',
            name: 'Tourist Help Center',
            latitude: 40.7580,
            longitude: -73.9855,
            address: '810 Seventh Avenue, New York, NY 10019',
            phone: '+1-555-404-4001',
            available247: false,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'help_center',
            name: "Women's Safety Center",
            latitude: 40.7489,
            longitude: -73.9680,
            address: '470 Park Avenue South, New York, NY 10016',
            phone: '+1-555-404-4002',
            available247: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'help_center',
            name: 'Crisis Hotline Center',
            latitude: 40.7410,
            longitude: -73.9937,
            address: '50 Broadway, New York, NY 10004',
            phone: '+1-555-404-4003',
            available247: true,
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(safetyResources).values(sampleSafetyResources);
    
    console.log('✅ Safety resources seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});